//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoilRecords
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Person_Id { get; set; }
        public string Person_name { get; set; }
        public string Person_mobile { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string DefaultPass { get; set; }
    }
}
