//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoilRecords
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Record_Id { get; set; }
        public string UserID { get; set; }
        public string Product_type { get; set; }
        public string Loading_depot { get; set; }
        public System.DateTime Discharge_date { get; set; }
        public System.TimeSpan Discharge_time { get; set; }
        public double Product_temperature { get; set; }
        public double Density_at15 { get; set; }
        public double Quantity_discharged { get; set; }
        public double Temperature_observed { get; set; }
        public double Density_observed { get; set; }
        public string Marker_certificate { get; set; }
        public string Invoice_number { get; set; }
        public double Sulphur_amount { get; set; }
        public string BRV_number { get; set; }
        public string Compartment_number { get; set; }
        public string Contains_water { get; set; }
        public string Driver_name { get; set; }
        public double Density_at15Observed { get; set; }
        public double Density_difference { get; set; }
    }
}
